### ISSUE TITLE
put NEWS bits in releases

### ISSUE THREAD

**Issue by sckott** [ropensci/historydata#15]
hey @lmullen   - We want all rOpenSci pkgs to consistently keep track of changes, following https://github.com/ropensci/onboarding/blob/master/packaging_guide.md#-news  
- you already keep a `NEWS` file, thanks!
- thanks for git tagging!
- Could you please use the [releases tab](https://github.com/ropensci/historydata/releases) on this repo to include the associated NEWS items for each tag/version ? thanks 😄

**Comment by lmullen** [comment]
This repo will get a new CRAN release this summer, so I'll sort out some weirdness with the tags and update the releases as a part of that package. Thanks, @sckott.

**Comment by sckott** [comment]
thanks!

**Comment by jrdnbradford** [comment]
In https://github.com/ropensci/historydata/commit/c77edc2e0787829bdbc742667b64fa5720d4400f the version was bumped from `0.1` to `0.2.9000` instead of `0.1.9000` so the release I just published is `0.3.0`: https://github.com/ropensci/historydata/pull/42. This release includes changes in `NEWS`.
