### ISSUE TITLE
`methodists`

### ISSUE THREAD

**Issue by maximromanov** [ropensci/historydata#22]
I cannot open `methodists` dataset; opening `methodists.rda` does not work either. Any thoughts?

(I am using your worksheets in class --- great work! Deeply appreciated and credited, of course!)

Running the following code:

```{r}
devtools::install_github("ropensci/historydata", force=TRUE)
library(historydata)
data(methodists)
methodists
```

Response:

```{r}
internal error -3 in R_decompress1Error: lazy-load database '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/historydata/data/Rdata.rdb' is corrupt
```

**Comment by lmullen** [comment]
I'm willing to be that you reinstalled the historydata package after already loading it. That is what the lazy load database corruption error is about. If you restart your R session it should work. If that's not the case, then let me know and we can reopen the issue.

**Comment by maximromanov** [comment]
That seemed to have worked. Thanks.
