### ISSUE TITLE
Add CESTA cities/populations dataset

### ISSUE THREAD

**Issue by lmullen** [ropensci/historydata#6]
Suggested by @hepplerj. 

https://github.com/cestastanford/historical-us-city-populations

**Comment by lmullen** [comment]
Hey, @hepplerj: I added the CESTA cities data to this package in a preliminary way. Here are the details if you want to look at it.

Relevant files:

- https://github.com/ropensci/historydata/blob/master/R/us_cities_pop.R
- https://github.com/ropensci/historydata/blob/master/data-raw/cesta-cities.R

I've also taken the liberty of adding you and Steiner as contributors, which is CRAN policy:

https://github.com/ropensci/historydata/blob/master/DESCRIPTION

**Comment by hepplerj** [comment]
Looks great, thanks!
